(function(){
  const esc=(value='')=>String(value).replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[ch]));
  const norm=(value='')=>String(value).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
  const teamFor=slug=>MASCOT_TEAMS[slug]||{team:'WNBA',primary:'#5b2bbf',secondary:'#d7ff42'};
  const initials=name=>String(name).split(/\s+/).filter(Boolean).slice(0,2).map(v=>v[0]).join('').toUpperCase();
  const posterBySlug={'atlanta-dream':'17989.png','chicago-sky':'17990.png','connecticut-sun':'17991.png','dallas-wings':'17992.png','golden-state-valkyries':'17993.png','indiana-fever':'17994.png','las-vegas-aces':'17995.png','new-york-liberty':'17996.png','minnesota-lynx':'17997.png','los-angeles-sparks':'17998.png','phoenix-mercury':'17999.png','portland-fire':'18000.png','seattle-storm':'18001.png','washington-mystics':'18172.jpg','toronto-tempo':'18174.jpg'};
  function card(item,retired=false){
    const team=teamFor(item.slug); const years=retired?item.years:item.debut;
    return `<article class="mascot-card" data-mascot-id="${esc(item.id)}" data-retired="${retired?'true':'false'}" style="--team:${team.primary};--team2:${team.secondary}" tabindex="0"><div class="mascot-card-photo" data-mascot-photo="${esc(item.id)}"><div class="mascot-fallback">${esc(initials(item.name))}</div></div><div class="mascot-card-body"><span class="mascot-team">${esc(team.team)} · ${esc(retired?'Retired':'Current')}</span><h3>${esc(item.displayName)}</h3><p class="mascot-species">${esc(item.species)}${years?` · ${esc(years)}`:''}</p><p class="mascot-teaser">${esc(item.bio)}</p><div class="mascot-card-actions"><button type="button" data-open-mascot="${esc(item.id)}">Open bio</button><a href="/team.html?team=${esc(item.slug)}">Team page →</a></div></div></article>`;
  }
  async function loadPhoto(host,item){
    if(!host||host.dataset.loaded==='true')return; host.dataset.loaded='true';
    let image=item.image||'',credit=item.imageCredit||'',creditUrl=item.source||'';
    if(!image&&item.source){try{const r=await fetch(`/api/culture-image?url=${encodeURIComponent(item.source)}`);const p=await r.json();if(p?.found){image=p.image;credit=item.imageCredit||'Photo source';creditUrl=p.sourceUrl||item.source;}}catch{}}
    if(!image){try{const r=await fetch(`/api/media?type=mascot&name=${encodeURIComponent(item.displayName)}`);const p=await r.json();if(p?.found){image=p.item?.image||'';credit=p.item?.creator||'Photo source';creditUrl=p.item?.sourceUrl||creditUrl;}}catch{}}
    if(!image&&posterBySlug[item.slug]){image=`/assets/images/${posterBySlug[item.slug]}`;credit='Team artwork';creditUrl=`/team.html?team=${item.slug}`;}
    if(!image)return;
    const img=document.createElement('img');img.src=image;img.alt=`${item.displayName}, ${teamFor(item.slug).team} mascot`;img.loading='lazy';img.decoding='async';img.addEventListener('error',()=>img.remove(),{once:true});host.querySelector('.mascot-fallback')?.remove();host.prepend(img);
    if(credit){const tag=document.createElement(creditUrl?'a':'span');tag.className='photo-credit';tag.textContent=credit;if(creditUrl){tag.href=creditUrl;tag.target='_blank';tag.rel='noopener';}host.appendChild(tag);}
  }
  const all=[...CURRENT_MASCOTS,...RETIRED_MASCOTS]; const byId=Object.fromEntries(all.map(item=>[item.id,item]));
  function hydrate(root=document){root.querySelectorAll('[data-mascot-photo]').forEach(host=>loadPhoto(host,byId[host.dataset.mascotPhoto]));}
  const search=document.getElementById('mascotSearch'),teamFilter=document.getElementById('mascotTeamFilter'),grid=document.getElementById('mascotGrid'),status=document.getElementById('mascotStatus');
  if(teamFilter){const teams=[...new Set(CURRENT_MASCOTS.map(item=>teamFor(item.slug).team))].sort();teamFilter.innerHTML='<option value="">All mascot teams</option>'+teams.map(team=>`<option>${esc(team)}</option>`).join('');}
  function renderCurrent(){if(!grid)return;const q=norm(search?.value||'').trim(),team=teamFilter?.value||'';const visible=CURRENT_MASCOTS.filter(item=>{const teamName=teamFor(item.slug).team;const hay=norm(`${item.displayName} ${item.species} ${teamName} ${item.bio} ${(item.facts||[]).join(' ')}`);return(!q||hay.includes(q))&&(!team||team===teamName)});grid.innerHTML=visible.map(item=>card(item,false)).join('')||'<div class="culture-loading">No mascot match yet. Try another name, team or animal.</div>';if(status)status.textContent=`Showing ${visible.length} of ${CURRENT_MASCOTS.length} current mascots.`;hydrate(grid);}
  function renderRetired(){const host=document.getElementById('retiredMascotGrid');if(!host)return;host.innerHTML=RETIRED_MASCOTS.map(item=>card(item,true)).join('');hydrate(host);}
  function renderVacancies(){const host=document.getElementById('mascotVacancyGrid');if(!host)return;host.innerHTML=MASCOT_VACANCIES.map(item=>`<article class="mascot-vacancy"><span>${esc(item.status)}</span><h3>${esc(item.team)}</h3><p>${esc(item.note)}</p><a href="/team.html?team=${esc(item.slug)}">Open team page →</a></article>`).join('');}
  const dialog=document.getElementById('mascotDialog'),body=document.getElementById('mascotDialogBody');
  function openMascot(id){const item=byId[id];if(!item||!dialog||!body)return;const team=teamFor(item.slug),retired=RETIRED_MASCOTS.includes(item);body.innerHTML=`<div class="mascot-dialog-layout" style="--team:${team.primary};--team2:${team.secondary}"><div class="mascot-dialog-photo" data-mascot-photo="${esc(item.id)}"><div class="mascot-fallback">${esc(initials(item.name))}</div></div><div class="mascot-dialog-copy"><p class="eyebrow">${esc(team.team)} · ${retired?'RETIRED MASCOT':'CURRENT MASCOT'}</p><h2>${esc(item.displayName)}</h2><div class="mascot-modal-species">${esc(item.species)}</div><div class="mascot-modal-meta">${item.debut?`<span>Debut: ${esc(item.debut)}</span>`:''}${item.years?`<span>Era: ${esc(item.years)}</span>`:''}${item.number?`<span>Jersey: ${esc(item.number)}</span>`:''}${item.pronouns?`<span>Pronouns: ${esc(item.pronouns)}</span>`:''}</div><p class="mascot-bio">${esc(item.bio)}</p>${item.facts?.length?`<div class="mascot-fact-grid">${item.facts.map(f=>`<span>${esc(f)}</span>`).join('')}</div>`:''}<div class="mascot-modal-actions"><a class="secondary" href="/team.html?team=${esc(item.slug)}">${esc(team.team)} team page →</a><a href="${esc(item.source)}" target="_blank" rel="noopener">${esc(item.sourceLabel||'Source')} ↗</a>${retired?'<a href="/locker-room.html#retired-mascots">Locker Room archive →</a>':''}</div></div></div>`;hydrate(body);if(typeof dialog.showModal==='function')dialog.showModal();else dialog.setAttribute('open','');}
  document.addEventListener('click',event=>{const trigger=event.target.closest('[data-open-mascot]');if(trigger){event.preventDefault();openMascot(trigger.dataset.openMascot);return;}const cardEl=event.target.closest('.mascot-card');if(cardEl&&!event.target.closest('a'))openMascot(cardEl.dataset.mascotId);});
  document.addEventListener('keydown',event=>{if((event.key==='Enter'||event.key===' ')&&event.target.classList?.contains('mascot-card')){event.preventDefault();openMascot(event.target.dataset.mascotId);}});
  document.getElementById('mascotDialogClose')?.addEventListener('click',()=>dialog?.close());dialog?.addEventListener('click',event=>{if(event.target===dialog)dialog.close();});
  search?.addEventListener('input',renderCurrent);teamFilter?.addEventListener('change',renderCurrent);document.getElementById('mascotReset')?.addEventListener('click',()=>{if(search)search.value='';if(teamFilter)teamFilter.value='';renderCurrent();});
  document.querySelectorAll('[data-mascot-updated]').forEach(el=>el.textContent=MASCOT_UPDATED);
  const queryTeam=new URLSearchParams(location.search).get('team');if(queryTeam&&teamFilter){const teamName=teamFor(queryTeam).team;if([...teamFilter.options].some(o=>o.value===teamName))teamFilter.value=teamName;}
  renderCurrent();renderRetired();renderVacancies();
})();
