(()=>{
  const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#039;'}[c]));
  const norm=(v='')=>String(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'');
  const num=v=>v!==null&&v!==undefined&&v!==''&&Number.isFinite(Number(v))?Number(v):null;
  const one=v=>num(v)===null?'—':num(v).toFixed(1);
  const signed=v=>num(v)===null?'—':`${num(v)>0?'+':''}${num(v).toFixed(1)}`;
  const pct=v=>{const n=num(v);return n===null?'—':`${(Math.abs(n)<=1?n*100:n).toFixed(1)}%`;};
  const rate100=v=>{const n=num(v);return n===null?'—':(Math.abs(n)<=1?n*100:n).toFixed(1);};
  const teamSlug=new URLSearchParams(location.search).get('team')||'';
  if(!teamSlug)return;

  const TEAMS=[
    ['atlanta-dream','Atlanta Dream','ATL'],['chicago-sky','Chicago Sky','CHI'],['connecticut-sun','Connecticut Sun','CON'],['dallas-wings','Dallas Wings','DAL'],['golden-state-valkyries','Golden State Valkyries','GSV'],['indiana-fever','Indiana Fever','IND'],['las-vegas-aces','Las Vegas Aces','LVA'],['los-angeles-sparks','Los Angeles Sparks','LAS'],['minnesota-lynx','Minnesota Lynx','MIN'],['new-york-liberty','New York Liberty','NYL'],['phoenix-mercury','Phoenix Mercury','PHX'],['portland-fire','Portland Fire','PDX'],['seattle-storm','Seattle Storm','SEA'],['toronto-tempo','Toronto Tempo','TOR'],['washington-mystics','Washington Mystics','WAS']
  ].map(([slug,name,abbr])=>({slug,name,abbr}));
  const currentTeam=TEAMS.find(t=>t.slug===teamSlug)||null;
  const byName=new Map(TEAMS.map(team=>[norm(team.name),team]));

  function addCss(href,key){if(document.querySelector(`link[data-${key}]`))return;const link=document.createElement('link');link.rel='stylesheet';link.href=href;link.dataset[key]='true';document.head.appendChild(link);}
  addCss('/rivalry.css?v=20260823-v8','rivalryCss');
  addCss(`/team-dna.css?v=20260823-v7&cb=${Date.now()}`,'teamDnaCss');

  function addDnaNav(){
    const nav=document.querySelector('#teamLocalNav .team-local-nav-inner');if(!nav)return null;
    let link=nav.querySelector('a[href="#team-dna"],[data-team-dna-link]');
    if(!link){link=document.createElement('a');link.href='#team-dna';link.textContent='Team DNA';link.dataset.teamDnaLink='true';const now=nav.querySelector('a[href="#whats-happening"]');now?now.insertAdjacentElement('afterend',link):nav.prepend(link);}
    link.href='#team-dna';link.dataset.teamDnaLink='true';return link;
  }

  function ensureDnaSection(){
    const live=document.getElementById('whats-happening');if(!live)return null;
    let section=document.getElementById('team-dna')||document.getElementById('team-dna-bootstrap');
    if(!section){section=document.createElement('section');live.insertAdjacentElement('afterend',section);}
    section.id='team-dna';section.className='team-content team-dna-section';
    section.innerHTML='<div class="team-section-heading dream-heading-row"><div><p class="kicker">THE TEAM DNA</p><h2>How they win, where they hurt you, and where they’re vulnerable.</h2><p>Possession-based ratings, efficiency, style and situational context for the 2026 season.</p></div><p class="dna-feed-status" id="teamDnaStatus"><span aria-hidden="true"></span> Building the profile…</p></div><div id="teamDnaBody"><div class="dna-loading">Reading the numbers behind the record…</div></div>';
    addDnaNav();return section;
  }

  const dnaSection=ensureDnaSection();
  if(teamSlug==='cleveland-sirens'&&dnaSection){
    document.getElementById('teamDnaBody').innerHTML='<div class="dna-empty"><strong>The Sirens’ DNA starts in 2028.</strong><p>Offensive rating, defensive rating, pace, efficiency and Team Temperature will populate after Cleveland begins official WNBA play.</p></div>';
    document.getElementById('teamDnaStatus').textContent='Expansion profile · metrics begin in 2028';
  }

  const rankText=(rank,pool=15)=>num(rank)===null?'—':`#${Number(rank)} of ${Number(pool)||15}`;
  const poolFor=(row,field)=>Number((row&&row[`${field}RankPool`])||15);
  const tone=(rank,pool=15,neutral=false)=>{if(neutral||num(rank)===null)return 'dna-neutral';const total=Math.max(3,Number(pool)||15),third=Math.ceil(total/3),r=Number(rank);return r<=third?'dna-strong':r>total-third?'dna-watch':'dna-middle';};
  const valueCard=(label,value,rank,note,opts={})=>`<article class="dna-score-card ${tone(rank,opts.pool||15,opts.neutral)}${opts.feature?' dna-feature':''}"><span>${esc(label)}</span><strong>${esc(value)}</strong><small>${esc(rankText(rank,opts.pool||15))}${note?` · ${esc(note)}`:''}</small></article>`;
  const letterGrade=value=>{const score=Math.round(num(value)||0);if(score>=97)return 'A+';if(score>=93)return 'A';if(score>=90)return 'A−';if(score>=87)return 'B+';if(score>=83)return 'B';if(score>=80)return 'B−';if(score>=77)return 'C+';if(score>=73)return 'C';if(score>=70)return 'C−';if(score>=67)return 'D+';if(score>=63)return 'D';if(score>=60)return 'D−';return 'F';};
  const metricRow=(label,value,rank,note,opts={})=>`<div class="dna-metric-row ${tone(rank,opts.pool||15,opts.neutral)}"><div><span>${esc(label)}</span>${note?`<small>${esc(note)}</small>`:''}</div><strong>${esc(value)}</strong><b>${esc(rankText(rank,opts.pool||15))}</b></div>`;
  const streakScore=value=>{const text=String(value||'').toUpperCase(),count=Number(text.replace(/[^0-9]/g,''))||0;if(text.startsWith('W'))return count>=5?100:count>=3?85:65;if(text.startsWith('L'))return count>=5?5:count>=3?20:35;return 50;};
  function temperature(row,standing){
    const rating=num(row.overallRating)===null?50:num(row.overallRating),parts=String(standing?.last_ten||'').split('-').map(Number);
    const lastTenPct=Number.isFinite(parts[0])&&Number.isFinite(parts[1])&&(parts[0]+parts[1])?parts[0]/(parts[0]+parts[1]):(num(row.winPct)===null?.5:num(row.winPct));
    const score=.55*rating+.35*(lastTenPct*100)+.10*streakScore(standing?.streak);let label='😌 STEADY',cls='temp-steady';
    if(score>=82){label='🔥 SCORCHING';cls='temp-scorching';}else if(score>=68){label='🌡️ HEATING UP';cls='temp-heating';}else if(score<32){label='🚨 IN TROUBLE';cls='temp-trouble';}else if(score<48){label='🥶 COLD';cls='temp-cold';}
    const netRank=num(row.netRtgRank)!==null?`#${row.netRtgRank} net rating`:'net rating still calculating';return {label,cls,copy:`${standing?.last_ten||'—'} over the last 10, ${netRank}, ${standing?.streak||'—'} current streak.`};
  }
  function renderDna(row,standing,dna){
    if(!document.getElementById('teamDnaBody'))return;
    if(num(row.oppPpg)===null&&num(row.ppg)!==null&&num(row.mov)!==null)row.oppPpg=num(row.ppg)-num(row.mov);
    const temp=temperature(row,standing),ratingPool=Number(row.overallRankPool||dna.teamCount||15);
    const top=`<div class="dna-score-grid">${valueCard('OFFENSIVE RATING',one(row.offRtg),row.offRtgRank,'points / 100 poss.',{pool:poolFor(row,'offRtg')})}${valueCard('DEFENSIVE RATING',one(row.defRtg),row.defRtgRank,'allowed / 100 poss.',{pool:poolFor(row,'defRtg')})}${valueCard('NET RATING',signed(row.netRtg),row.netRtgRank,'per 100 poss.',{pool:poolFor(row,'netRtg')})}${valueCard('OVERALL RATING · W RATING',`${Math.round(num(row.overallRating)||0)} / 100 · ${letterGrade(row.overallRating)}`,row.overallRank,'We Know the W composite',{pool:ratingPool,feature:true})}${valueCard('PACE OF PLAY',one(row.pace),row.paceRank,'possessions / 40 min.',{pool:poolFor(row,'pace'),neutral:true})}<article class="dna-temperature ${temp.cls}"><span>TEAM TEMPERATURE</span><strong>${esc(temp.label)}</strong><small>${esc(temp.copy)}</small></article></div>`;
    const offense=[['Points / game',one(row.ppg),row.ppgRank,'raw scoring'],['Effective FG%',pct(row.offEfgPct),row.offEfgPctRank,'shot-value efficiency'],['True shooting',pct(row.tsPct),row.tsPctRank,'2s + 3s + free throws'],['3-point %',pct(row.threePct),row.threePctRank,'accuracy from deep'],['Assists / game',one(row.ast),row.astRank,'ball movement'],['Turnover %',pct(row.offTovPct),row.offTovPctRank,'lower is better'],['Offensive rebound %',pct(row.orbPct),row.orbPctRank,'extra possessions'],['Free throw rate',rate100(row.ftr),row.ftrRank,'FTA per 100 FGA']];
    const defense=[['Opponent points / game',one(row.oppPpg),row.oppPpgRank,'lower is better'],['Opponent eFG%',pct(row.defEfgPct),row.defEfgPctRank,'shot quality allowed'],['Forced turnover %',pct(row.defTovPct),row.defTovPctRank,'higher is better'],['Defensive rebound %',pct(row.drbPct),row.drbPctRank,'finish the stop'],['Steals / game',one(row.stl),row.stlRank,'takeaways'],['Blocks / game',one(row.blk),row.blkRank,'rim disruption'],['Defensive rating',one(row.defRtg),row.defRtgRank,'allowed / 100 poss.'],['Opponent FT/FGA',rate100(row.defFtFga),null,'free throws allowed / 100 FGA',{neutral:true}]];
    const situational=[['Home record',String(standing?.home_record||'—'),null,'home floor',{neutral:true}],['Road record',String(standing?.road_record||'—'),null,'away games',{neutral:true}],['Last 10',String(standing?.last_ten||'—'),null,'recent form',{neutral:true}],['Current streak',String(standing?.streak||'—'),null,'right now',{neutral:true}],['Average margin',signed(row.mov),row.movRank,'points / game'],['Strength of schedule',signed(row.sos),row.sosRank,'higher = tougher',{neutral:true}],['Expected W–L',`${num(row.expectedWins)===null?'—':num(row.expectedWins)}–${num(row.expectedLosses)===null?'—':num(row.expectedLosses)}`,null,'point-differential model',{neutral:true}],['SRS',signed(row.srs),row.srsRank,'margin + schedule strength']];
    const board=(kicker,title,copy,rows)=>`<article class="dna-board"><div class="dna-board-head"><span>${esc(kicker)}</span><h3>${esc(title)}</h3><p>${esc(copy)}</p></div><div class="dna-metric-list">${rows.map(item=>metricRow(item[0],item[1],item[2],item[3],item[4]||{})).join('')}</div></article>`;
    document.getElementById('teamDnaBody').innerHTML=`${top}<div class="dna-board-grid">${board('OFFENSE','HOW THEY EAT','Where the points and possessions come from.',offense)}${board('DEFENSE','NO FLY ZONE','How well they erase advantages and end possessions.',defense)}${board('SITUATIONAL PULSE','WHEN IT GETS TIGHT','Recent form, splits and season context.',situational)}</div><div class="dna-source"><div><strong>Reading the board</strong><p>Green = top third of the WNBA, yellow = middle third, red = bottom third. Pace and strength of schedule stay neutral.</p></div><div><strong>Sources + methodology</strong><p>2026 team metrics from Basketball-Reference. Live record splits from We Know the W’s standings feed. W Rating and Team Temperature are We Know the W composites.</p></div></div>`;
    document.getElementById('teamDnaStatus').innerHTML=`<span aria-hidden="true"></span> ${dna.teamCount||15} teams ranked`;
  }
  async function loadDna(){
    if(!currentTeam||teamSlug==='cleveland-sirens'||!dnaSection)return;
    try{
      const [dnaResult,statsResult]=await Promise.allSettled([
        fetch(`/api/team-dna?season=2026&direct=1&v=20260823-v8&cb=${Date.now()}`,{headers:{Accept:'application/json','Cache-Control':'no-cache'},cache:'no-store'}).then(async r=>{const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||data.detail||`Team DNA API returned ${r.status}`);return data;}),
        fetch(`/api/stats?season=2026&teamDna=1&cb=${Date.now()}`,{headers:{Accept:'application/json','Cache-Control':'no-cache'},cache:'no-store'}).then(async r=>{const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||`Standings API returned ${r.status}`);return data;})
      ]);
      if(dnaResult.status!=='fulfilled')throw dnaResult.reason;
      const dna=dnaResult.value,row=(dna.teams||[]).find(item=>norm(item.name)===norm(currentTeam.name));if(!row)throw new Error(`No Team DNA row matched ${currentTeam.name}.`);
      const standings=statsResult.status==='fulfilled'?(statsResult.value.standings||[]):[],standing=standings.find(item=>norm(item.team?.full_name)===norm(currentTeam.name))||null;renderDna(row,standing,dna);
    }catch(error){document.getElementById('teamDnaBody').innerHTML=`<div class="dna-empty"><strong>Team DNA is attached, but the stat feed could not finish.</strong><p>${esc(error?.message||'The analytics source is reconnecting.')}</p></div>`;document.getElementById('teamDnaStatus').textContent='Analytics feed temporarily unavailable';}
  }
  loadDna();

  if(teamSlug==='cleveland-sirens')return;

  function edge(record={wins:0,losses:0}){if(record.wins>record.losses)return 'Leading';if(record.losses>record.wins)return 'Trailing';return Number(record.wins||0)+Number(record.losses||0)?'Even':'No meetings';}
  function seriesClass(record={wins:0,losses:0}){const w=Number(record.wins||0),l=Number(record.losses||0);if(w+l===0)return 'no-meeting';if(w>l)return 'series-win';if(l>w)return 'series-loss';return 'series-even';}
  function rowClass(record={wins:0,losses:0}){const cls=seriesClass(record);return cls==='series-win'?'row-win':cls==='series-loss'?'row-loss':cls==='series-even'?'row-even':'row-no-meeting';}
  function addRecords(a={wins:0,losses:0},b={wins:0,losses:0}){return {wins:Number(a.wins||0)+Number(b.wins||0),losses:Number(a.losses||0)+Number(b.losses||0)};}
  function lossPct(record={wins:0,losses:0}){const total=Number(record.wins||0)+Number(record.losses||0);return total?Math.round(Number(record.losses||0)/total*100):0;}
  function label(p){if(p<=35)return 'You own this stop';if(p<=50)return 'Light traffic';if(p<=60)return 'Rush hour';if(p<=70)return 'Uphill transfer';return 'Service disruption';}
  function isCupFinal(game={}){const date=String(game.date||game.startTimeUtc||'').slice(0,10);if(date!=='2026-06-30')return false;const pair=[norm(game.homeTeam),norm(game.awayTeam)].sort().join('|');return pair===[norm('Las Vegas Aces'),norm('New York Liberty')].sort().join('|');}

  function ensureSection(){
    let section=document.getElementById('head-to-head');if(section)return section;
    const live=document.getElementById('whats-happening');if(!live)return null;
    section=document.createElement('section');section.className='team-content team-rivalry-section';section.id='head-to-head';section.innerHTML='<div class="team-section-heading"><p class="kicker">NO LOVE LOST · HEAD TO HEAD</p><h2>Who has the upper hand?</h2><p>See the 2026 season series beside the all-time regular-season franchise line.</p></div><div id="teamRivalryBody" class="team-rivalry-table"><div class="page-note"><strong>Loading head-to-head records…</strong><p>Connecting the current season and historical rivalry archive.</p></div></div><div class="dream-source-row"><a href="/no-love-lost.html">Open the league rivalry board →</a><a href="/franchise-family-tree.html">Franchise family tree →</a></div>';
    const dna=document.getElementById('team-dna');dna?dna.insertAdjacentElement('afterend',section):live.insertAdjacentElement('afterend',section);
    const nav=document.querySelector('.team-local-nav-inner');if(nav&&!nav.querySelector('a[href="#head-to-head"]')){const a=document.createElement('a');a.href='#head-to-head';a.textContent='Head to head';const dnaLink=nav.querySelector('a[href="#team-dna"]');dnaLink?dnaLink.insertAdjacentElement('afterend',a):nav.querySelector('a[href="#whats-happening"]')?.insertAdjacentElement('afterend',a);}return section;
  }
  function payloadFromStats(stats={}){const matrix={};TEAMS.forEach(team=>matrix[team.slug]={});const games=(Array.isArray(stats.pastGames)?stats.pastGames:Array.isArray(stats.recentResults)?stats.recentResults:[]).filter(game=>!isCupFinal(game));for(const game of games){const home=byName.get(norm(game.homeTeam)),away=byName.get(norm(game.awayTeam)),hs=Number(game.homeScore),as=Number(game.awayScore);if(!home||!away||!Number.isFinite(hs)||!Number.isFinite(as)||hs===as)continue;const hr=matrix[home.slug][away.slug]||{wins:0,losses:0},ar=matrix[away.slug][home.slug]||{wins:0,losses:0};if(hs>as){hr.wins++;ar.losses++;}else{hr.losses++;ar.wins++;}matrix[home.slug][away.slug]=hr;matrix[away.slug][home.slug]=ar;}const rows={};for(const team of TEAMS)rows[team.slug]=TEAMS.filter(o=>o.slug!==team.slug).map(opponent=>{const r=matrix[team.slug][opponent.slug]||{wins:0,losses:0};return {opponent,season:{...r,edge:edge(r)}};});const count=Math.round(TEAMS.reduce((sum,team)=>sum+Object.values(matrix[team.slug]).reduce((s,r)=>s+r.wins+r.losses,0),0)/2);return {rows,coverage:{seasonGameCount:count},updatedAt:stats.updatedAt||new Date().toISOString(),fallback:true};}
  async function currentPayload(){let primaryError=null;try{const r=await fetch(`/api/rivalry-current?season=2026&v=20260823-3&cb=${Date.now()}`,{headers:{Accept:'application/json','Cache-Control':'no-cache'},cache:'no-store'}),data=await r.json().catch(()=>({}));if(!r.ok||!Number(data?.coverage?.seasonGameCount))throw new Error(data.error||'Current rivalry feed returned no completed games.');return data;}catch(error){primaryError=error;const r=await fetch(`/api/stats?season=2026&headToHead=1&cb=${Date.now()}`,{headers:{Accept:'application/json','Cache-Control':'no-cache'},cache:'no-store'}),stats=await r.json().catch(()=>({}));if(!r.ok||stats.error)throw new Error(stats.error||primaryError.message||'Rivalry feed unavailable');const data=payloadFromStats(stats);if(!Number(data.coverage?.seasonGameCount))throw new Error(primaryError.message||'No completed games were available.');return data;}}
  async function historyPayload(){const r=await fetch(`/api/rivalries?season=2026&team=${encodeURIComponent(teamSlug)}&v=20260824-v7&cb=${Date.now()}`,{headers:{Accept:'application/json','Cache-Control':'no-cache'},cache:'no-store'}),data=await r.json().catch(()=>({}));if(!r.ok||!Number(data?.coverage?.allGameCount))throw new Error(data.error||'Historical rivalry archive unavailable');return data;}
  function mergeRows(current,history){const currentRows=current.rows?.[teamSlug]||[],historyRows=Array.isArray(history?.rows)?history.rows:history?.rows?.[teamSlug]||[],historyByOpponent=new Map(historyRows.map(row=>[row.opponent?.slug,row])),includes2026=Array.isArray(history?.coverage?.completedYears)&&history.coverage.completedYears.includes(2026);return currentRows.map(row=>{const old=historyByOpponent.get(row.opponent.slug);let allTime=old?.allTime?{wins:Number(old.allTime.wins||0),losses:Number(old.allTime.losses||0)}:{wins:0,losses:0};if(!includes2026)allTime=addRecords(allTime,row.season);return {...row,allTime:{...allTime,edge:edge(allTime)},historyAvailable:true};});}
  function renderRivalry(rows=[],currentCoverage={},history=null,fallback=false,historyError=''){const body=document.getElementById('teamRivalryBody');if(!body)return;if(!rows.length){body.innerHTML='<div class="page-note"><strong>No rivalry rows were returned.</strong></div>';return;}body.innerHTML=`<div class="team-rivalry-row head"><span>Opponent</span><span>2026</span><span>2026 edge</span><span>All time</span><span>All-time edge</span><span>Struggle meter</span></div>${rows.map(r=>{const seasonCls=seriesClass(r.season),row=rowClass(r.season),hasHistory=r.historyAvailable&&r.allTime,allCls=hasHistory?seriesClass(r.allTime):'no-meeting',loss=hasHistory?lossPct(r.allTime):0,meetings=hasHistory?Number(r.allTime.wins||0)+Number(r.allTime.losses||0):0,allRecord=hasHistory?`${r.allTime.wins}-${r.allTime.losses}`:'—',allEdge=hasHistory?(r.allTime.edge||edge(r.allTime)):'Archive unavailable',meterText=hasHistory?(meetings?`${loss}% · ${esc(label(loss))} · all time`:'No all-time meetings'):'All-time archive unavailable';return `<div class="team-rivalry-row ${row}"><a class="team-rivalry-opponent" href="/team.html?team=${encodeURIComponent(r.opponent.slug)}"><strong>${esc(r.opponent.name)}</strong><span>→</span></a><strong><span class="series-pill ${seasonCls}">${r.season.wins}-${r.season.losses}</span></strong><span><span class="series-edge-pill ${seasonCls}">${esc(r.season.edge||edge(r.season))}</span></span><strong><span class="series-pill ${allCls}">${allRecord}</span></strong><span><span class="series-edge-pill ${allCls}">${esc(allEdge)}</span></span><div class="struggle-meter"><div class="struggle-track"><div class="struggle-fill" style="width:${hasHistory&&meetings?Math.max(0,Math.min(100,loss)):0}%"></div></div><small>${meterText}</small></div></div>`;}).join('')}`;const games=Number(currentCoverage.seasonGameCount||0),allGames=Number(history?.coverage?.allGameCount||0);body.insertAdjacentHTML('beforeend',`<div class="page-note"><strong>${games} completed 2026 regular-season games connected.</strong><p>${fallback?'Live Stats fallback is active. ':''}${history?`${allGames} historical regular-season games connected.`:`All-time archive could not connect${historyError?`: ${esc(historyError)}`:''}.`}</p></div>`);}
  const section=ensureSection();if(!section)return;(async()=>{const current=await currentPayload();let history=null,historyError='';try{history=await historyPayload();}catch(error){historyError=error.message||'Historical rivalry archive unavailable';}const rows=history?mergeRows(current,history):(current.rows?.[teamSlug]||[]).map(row=>({...row,allTime:null,historyAvailable:false}));renderRivalry(rows,current.coverage||{},history,Boolean(current.fallback),historyError);})().catch(error=>{const body=document.getElementById('teamRivalryBody');if(body)body.innerHTML=`<div class="page-note"><strong>2026 rivalry records are temporarily unavailable.</strong><p>${esc(error.message||'Try again shortly.')}</p></div>`;});
})();
